server:
  port: 8884

spring:
  #mysql数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.27.112.11:3306/wx?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: k2UpMsZs

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      db-type: MYSQL
      logic-delete-value: 0
      logic-not-delete-value: 1
  mapper-locations: classpath*:/mapper/*.xml

log:
  charset: UTF-8
  level: INFO
  path: ./logs