server:
  port: 8884

spring:
  #mysql数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.96.135.197:3306/wx?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Zbp1gpuigiof8t5483fo8
      connection-init-sqls: set names utf8mb4
  redis:
    database: 1
    host: 47.96.135.197
    port: 6379
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mybatis/*/*.xml
  type-aliases-package: com.example.demo.dao.entity

log:
  charset: UTF-8
  level: INFO
  path: ./logs